version: 2.1

jobs:
  eslint:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: npm install eslint@8.48.0 # install dependencies
      - run: npx eslint .
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx # run the eslint command

workflows:
  my-workflow:
    jobs:
      - eslint:
          filters:
            branches:
              only: master